### ISSUE TITLE
这个库可以在VSCode环境下配置使用吗？

### ISSUE THREAD

**Issue by cocobase** [ai4trade/XtQuant#1]
目前在迅投极速交易系统的环境中开发策略的时候，编辑调试都不是很方便
可以使用VSCODE环境配置配置这颗额外的库来完成策略的开发、行情的订阅、数据的回测吗？
第一次看到这个库，简单看了一些文档，直观上理解是可以的
但是作者是否有更详细的配置说明文档？

**Comment by ai4trade** [comment]
> 

mini QMT可以的，使用xtquant库：https://github.com/ai4trade/XtQuant/blob/main/xtquant/doc/xttrader.md
