### ISSUE TITLE
Python 3.10 + vscode 一直无法解决找不到模块的问题No module named 'xtquant.IPythonApiClient'

### ISSUE THREAD

**Issue by cocobase** [ai4trade/XtQuant#2]
PS C:\Users\dell\Desktop\stock\XtQuant> & C:/Python310/python.exe c:/Users/dell/Desktop/stock/XtQuant/src/mytest.py
Traceback (most recent call last):
  File "c:\Users\dell\Desktop\stock\XtQuant\src\mytest.py", line 10, in <module>
    from xtquant import xtdata
  File "C:\Python310\lib\site-packages\xtquant\xtdata.py", line 7, in <module>
    from .IPythonApiClient import IPythonApiClient as RPCClient
ModuleNotFoundError: No module named 'xtquant.IPythonApiClient'
PS C:\Users\dell\Desktop\stock\XtQuant> 

尝试了各种方法，把 xtquant 目录拷贝到了   "C:\Python310\lib\site-packages\xtquant\xtdata.py" 也无法正确加载

另外一个尝试：在代码头部加入以下路径信息也无法找到
sys.path.append("C:\\Users\\dell\\Desktop\\stock\\XtQuant")
sys.path.append("C:\\Users\\dell\\Desktop\\stock\\XtQuant\\xtquant")

如何解决？是否是版本问题？一定要 Python3.6 3.7 or 3.8 才可以吗？

**Comment by ai4trade** [comment]
必须：3.6-3.8

**Comment by cocobase** [comment]
更换Python版本到3.8 ，还是老问题啊

PS C:\Users\dell\Desktop\stock\XtQuant> & C:/Python38/python.exe c:/Users/dell/Desktop/stock/XtQuant/app_xtdata.py
Traceback (most recent call last):
  File "c:/Users/dell/Desktop/stock/XtQuant/app_xtdata.py", line 3, in <module>
    from xtquant import xtdata
  File "c:\Users\dell\Desktop\stock\XtQuant\xtquant\xtdata.py", line 7, in <module>
    from .IPythonApiClient import IPythonApiClient as RPCClient
ModuleNotFoundError: No module named 'xtquant.IPythonApiClient'
PS C:\Users\dell\Desktop\stock\XtQuant>

**Comment by haydengao** [comment]
你这个感觉是环境问题，pip show ipython看看输出是啥

**Comment by cocobase** [comment]
目前解决了，将 xtquant 目录 拷贝到  python 安装目录下的  lib/site_packages/下 就可以了

**Comment by cocobase** [comment]
运行程序已经不会发生错误，但是运行结束没有任何反馈和输出
我运行了 app_xtdata.py
在程序第一行添加了一句 print，也不会有输出
![xquant-error](https://user-images.githubusercontent.com/60334709/183836336-c265c237-97c2-4a5d-aa77-589449fad066.png)
