### ISSUE TITLE
python 3.8 环境报错：No module named 'xtquant.IPythonApiClient'

### ISSUE THREAD

**Issue by laye0619** [ai4trade/XtQuant#3]
这个是不是只能运行在windows环境？Linux环境我建立了python 3.8，手动安装了xtquant，修改了xtdata.ini里面的地址，但是第一步import就报这个错误了

<img width="580" alt="image" src="https://user-images.githubusercontent.com/9484313/186794587-f571f01b-f974-4413-aa11-5e34a703ca54.png">

**Comment by ai4trade** [comment]
> 这个是不是只能运行在windows环境？Linux环境我建立了python 3.8，手动安装了xtquant，修改了xtdata.ini里面的地址，但是第一步import就报这个错误了
> 
> <img alt="image" width="580" src="https://user-images.githubusercontent.com/9484313/186794587-f571f01b-f974-4413-aa11-5e34a703ca54.png">

只能Windows，因为用到的pyd文件是Windows下的DLL生成的

**Comment by laye0619** [comment]
实盘量化果然是windows的天下啊！
