### ISSUE TITLE
无法正确Import 模块 PYD

### ISSUE THREAD

**Issue by cocobase** [ai4trade/XtQuant#5]
Python3.8.10环境
xtquant正确拷贝到site_packages目录下，搜索路径正确
跟踪执行的过程发现无法正确导入PYD模块
from .IPythonApiClient import IPythonApiClient as RPCClient 的时候没有报任何错误
程序直接终止退出
问题在哪里？

**Comment by ai4trade** [comment]
运行Python的目录不要出现xtquant文件夹，切换到一个空文件夹下运行看看

**Comment by cocobase** [comment]
按照建议，建立了一个空目录，写了一个最简单的main.py

```
import os,sys

print(os.path)
print(sys.path)

from xtquant import xtpythonclient
print("ok1")
from xtquant import xttrader
print("ok2")
from xtquant import xttype
print("ok3")
from xtquant import xtdata
print("ok4")
```
执行的结果是：
<module 'ntpath' from 'C:\\Python38\\lib\\ntpath.py'>
['c:\\Users\\dell\\Desktop\\stock\\testquant', 'C:\\Python38\\python38.zip', 'C:\\Python38\\DLLs', 'C:\\Python38\\lib', 'C:\\Python38', 'C:\\Python38\\lib\\site-packages']
ok1
ok2
ok3

最后一个 **ok4** 没有输出，无法import xtdata
我跟踪进入看发现到

> from .IPythonApiClient import IPythonApiClient as RPCClient

就无法跳出了

**Comment by cocobase** [comment]
为啥xtpythonclient可以正常import
但是IPythonApiClient就无法正常import 呢？

**Comment by ai4trade** [comment]
> 

这个没遇见过，其他人没问题的。你在https://open.gtja.com/door/v-index.html#/downList 下一个QMT，然后安装python库，拷贝到自己的python安装目录看看

**Comment by cocobase** [comment]
![屏幕截图 2022-09-12 170016](https://user-images.githubusercontent.com/60334709/189614417-ea02af70-38e5-48f1-bedc-b48e39ce9e7e.png)
我使用安信的QMT系统，并更新到了最新的版本，目前依然没有解决问题。
看起来是PYD文件本身的问题，因为另外一个xtpythonclient.pyd是可以正常导入的
![屏幕截图 2022-09-12 170423](https://user-images.githubusercontent.com/60334709/189615134-58aa10b3-5fda-41c3-ad24-eb3a5dff678d.png)

**Comment by Zoffy2018** [comment]
您好，我也遇到了相同的问题，显示DLL load failed while importing IPythonApiClient，请问您最后解决了吗？
